name: Docker Test API Setup
description: "Build and start test container with db for API"
runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Docker build
        uses: docker/setup-buildx-action@v3
      - name: Build test container
        run: docker compose -f docker-compose.test.yml build
        shell: bash
      - name: Start test container
        run: docker compose -f docker-compose.test.yml up -d db
        shell: bash
      - name: Wait for DB
        run: |
          until docker compose -f docker-compose.test.yml exec db pg_isready -U test_user; do
            echo "Waiting for Postgres..."
            sleep 2
          done
        shell: bash

